SHELL := /usr/bin/env bash

-include .env

.DEFAULT_GOAL := quick-load

QUICK_LOAD_CONTAINERS ?= 14
QUICK_LOAD_LOGS_PER_SEC ?= 5000
QUICK_LOAD_DURATION_SECONDS ?= 30
QUICK_LOAD_RAMP_SECONDS ?= 5
QUICK_LOAD_UNICRON_BASE_URL ?= https://localhost:8444
QUICK_LOAD_UNICRON_ADMIN_PASSWORD ?= $(UNICRON_ADMIN_PASSWORD)
QUICK_LOAD_UNICRON_ADMIN_PASSWORD_DISPLAY := $(if $(strip $(QUICK_LOAD_UNICRON_ADMIN_PASSWORD)),<redacted>,<empty>)

.PHONY: quick-load

quick-load: export QUICK_LOAD_UNICRON_ADMIN_PASSWORD := $(QUICK_LOAD_UNICRON_ADMIN_PASSWORD)
quick-load: export UNICRON_ADMIN_PASSWORD := $(QUICK_LOAD_UNICRON_ADMIN_PASSWORD)
quick-load:
	@set -e; \
	  export CONTAINERS="$(QUICK_LOAD_CONTAINERS)"; \
	  export LOGS_PER_SEC="$(QUICK_LOAD_LOGS_PER_SEC)"; \
	  export DURATION_SECONDS="$(QUICK_LOAD_DURATION_SECONDS)"; \
	  export UNICRON_BASE_URL="$(QUICK_LOAD_UNICRON_BASE_URL)"; \
	  export RAMP_SECONDS="$(QUICK_LOAD_RAMP_SECONDS)"; \
	  export QUICK_LOAD_UNICRON_ADMIN_PASSWORD; \
	  export UNICRON_ADMIN_PASSWORD; \
	  printf '%s\n' "Running quick-load with:"; \
	  printf 'QUICK_LOAD_CONTAINERS=%s\n' "$(QUICK_LOAD_CONTAINERS)"; \
	  printf 'QUICK_LOAD_LOGS_PER_SEC=%s\n' "$(QUICK_LOAD_LOGS_PER_SEC)"; \
	  printf 'QUICK_LOAD_RAMP_SECONDS=%s\n' "$(QUICK_LOAD_RAMP_SECONDS)"; \
	  printf 'QUICK_LOAD_DURATION_SECONDS=%s\n' "$(QUICK_LOAD_DURATION_SECONDS)"; \
	  printf 'QUICK_LOAD_UNICRON_BASE_URL=%s\n' "$(QUICK_LOAD_UNICRON_BASE_URL)"; \
	  printf 'QUICK_LOAD_UNICRON_ADMIN_PASSWORD=%s\n' "$(QUICK_LOAD_UNICRON_ADMIN_PASSWORD_DISPLAY)"; \
	  python3 lib/quick_load.py
